include:
    - project: cm-tm/cm-team/2-4.devops/pipeline-tpl-cluster
      ref: "1"
      file : base.yaml
    - project: cm-tm/cm-team/2-4.devops/pipeline-tpl-cluster
      ref: "1"
      file : image.yaml
    - project: cm-tm/cm-team/2-4.devops/pipeline-tpl-cluster
      ref: "1"
      file : deploy.yaml
    - project: cm-tm/cm-team/2-4.devops/pipeline-tpl-cluster
      ref: "1"
      file : maven.yaml  
    - local: 'variables.yaml'
    